username = 'lum-customer-hl_79a92981-zone-static'
password = ''
port = 22225

db_password = '12345'


api_token = '5315438005:AAE-edWPW7n4S7bJNvDvlzKFfWmDGCAlopY'

register = 'MasterPass'

colors_list ={
    'black': 'чёрный',
 	'silver': 'серебряный',
 	'gray': 'серый',
 	'white': 'белый',
 	'maroon': 'тёмно-бордовый',
 	'red': 'красный',
 	'purple': 'пурпурный',
 	'fuchsia': 'фуксия',
 	'green': 'зелёный',
 	'lime': 'лаймовый',
 	'olive': 'оливковый (желтовато-зелёный)',
 	'yellow': 'жёлтый',
 	'navy': 'тёмно-синий (морской)',
 	'blue': 'синий',
 	'teal': 'зеленовато-голубой',
 	'aqua': 'цвет морской волны',
 	'aliceblue': 'бледно-голубой',
 	'antiquewhite': 'античный белый',
 	'aquamarine': 'аквамарин (зеленовато-голубой)',
 	'azure': 'лазурный',
 	'beige': 'бежевый',
 	'bisque': 'фарфоровый',
 	'blanchedalmond': 'бланшированный миндаль',
 	'blueviolet': 'голубовато-фиолетовый',
 	'brown': 'коричневый',
 	'burlywood': 'тяжёлая древесина',
 	'cadetblue': 'синий курсантский',
 	'chartreuse': 'беледно-зелёный (зеленовато-жёлтый)',
 	'chocolate': 'шоколадный',
 	'coral': 'коралловый',
 	'cornflowerblue': 'васильковый',
 	'cornsilk': 'кукурузный',
 	'crimson': 'малиновый (тёмно-красный)',
 	'cyan': 'циан (голубой)',
 	'darkblue': 'тёмно-синий',
 	'darkcyan': 'тёмно-голубой',
 	'darkgoldenrod': 'тёмно-золотистый',
 	'darkgray': 'тёмно-серый',
 	'darkgreen': 'тёмно-зелёный',
 	'darkgrey': 'тёмно-серый',
 	'darkkhaki': 'тёмный хаки',
 	'darkmagenta': 'фиолетовый',
 	'darkolivegreen': 'тёмно-оливковый',
 	'darkorange': 'тёмно-оранжевый',
 	'darkorchid': 'тёмная орхидея',
 	'darkred': 'тёмно-красный',
 	'darksalmon': 'тёмно-лососевый',
 	'darkseagreen': 'тёмная морская волны',
 	'darkslateblue': 'тёмный грифельно-синий',
 	'darkslategray': 'тёмный грифельно-серый',
 	'darkturquoise': 'тёмно-бирюзовый',
 	'darkviolet': 'тёмно-фиолетовый',
 	'deeppink': 'глубокий розовый',
 	'deepskyblue': 'глубокий лазурный',
 	'dimgray': 'тускло-серый',
 	'dodgerblue': 'защитно-синий',
 	'firebrick': 'огнеупорный кирпич',
 	'floralwhite': 'цветочный белый',
 	'forestgreen': 'тёмно-зелёный',
 	'gainsboro': 'гейнсборо',
 	'ghostwhite': 'призрачно-белый',
 	'gold': 'золотой',
 	'goldenrod': 'золотистый',
 	'greenyellow': 'зелёно-жёлтый',
 	'grey': 'серый',
 	'honeydew': 'цвет нектара',
 	'hotpink': 'ярко-розовый',
 	'indianred': 'красный индийский',
 	'indigo': 'индиго',
 	'ivory': 'слоновая кость',
 	'khaki': 'хаки',
 	'lavender': 'лавандовый',
 	'lavenderblush': 'розовато-ловандовый',
 	'lawngreen': 'зелёный газон',
 	'lemonchiffon': 'лимонный шифон',
 	'lightblue': 'светло-синий',
 	'lightcoral': 'светло-коралловый',
 	'lightcyan': 'светло-голубой',
 	'lightgoldenrodyellow': 'светлый золотисто-жёлтый',
 	'lightgray': 'светло-серый',
 	'lightgreen': 'светло-зелёный',
 	'lightpink': 'светло-розовый',
 	'lightsalmon': 'светло-лососевый',
 	'lightseagreen': 'светлая морская волна',
 	'lightskyblue': 'светлый лазурный',
 	'lightslategray': 'светлый грифельно-серый',
 	'lightslategrey': 'светлый грифельно-серый',
 	'lightsteelblue': 'светло-серо-голубой',
 	'lightyellow': 'светло-жёлтый',
 	'limegreen': 'зелёный лайм',
 	'linen': 'льняной ',
 	'magenta': 'пурпурный ',
 	'mediumaquamarine': 'средний аквамарин',
 	'mediumblue': 'средний синий',
 	'mediumorchid': 'средний орхидейный',
 	'mediumpurple': 'средне-фиолетовый',
 	'mediumseagreen': 'средний цвет морской волны',
 	'mediumslateblue': 'средний грифельно-синий',
 	'mediumspringgreen': 'средний весенне-зелёный',
 	'mediumturquoise': 'средне-бирюзовый',
 	'mediumvioletred': 'средний фиолетово-красный',
 	'midnightblue': 'полуночно-синий',
 	'mintcream': 'мятно-кремовый',
 	'mistyrose': 'дымчато-розовый',
 	'moccasin': 'мокасин',
 	'navajowhite': 'белый навахо',
 	'oldlace': 'старые кружева',
 	'olivedrab': 'оливково-жёлтый',
 	'orange': 'оранжевый',
 	'orangered': 'оранжево-красный',
 	'orchid': 'светло-лиловый',
 	'palegoldenrod': 'бледно-золотистый',
 	'palegreen': 'бледно-зелёный',
 	'paleturquoise': 'бледно-бирюзовый',
 	'palevioletred': 'фиолетово-красный',
 	'papayawhip': 'взбитая папайя',
 	'peachpuff': 'слойные персики',
 	'peru': 'перуанский',
 	'pink': 'розовый',
 	'plum': 'сливовый',
 	'powderblue': 'пыльно-голубой',
 	'rosybrown': 'розово-коричневый',
 	'royalblue': 'ярко-синий',
 	'saddlebrown': 'бурый',
 	'salmon': 'оранжево-розовый (лососевый)',
 	'sandybrown': 'кожаный',
 	'seagreen': 'морской волны',
 	'seashell': 'морская ракушка',
 	'sienna': 'охра',
 	'skyblue': 'лазурный (небесно-голубой)',
 	'slateblue': 'грифельно-синий',
 	'slategray': 'грифельно-серый',
 	'slategrey': 'синевато-серый',
 	'snow': 'снежный',
 	'springgreen': 'весенне-зелёный',
 	'steelblue': 'синевато-стальной',
 	'tan': 'жёлто-коричневый',
 	'thistle': 'чертополох',
 	'tomato': 'томатный',
 	'turquoise': 'бирюзовый',
 	'violet': 'фиолетовый',
 	'wheat': 'пшеничный',
 	'whitesmoke': 'дымчато-белый',
 	'yellowgreen': 'жёлто-зелёный',
}

marks = {'BMW': 'БМВ',
		 'Chery': 'Чери',
		 'Chevrolet': 'Шевроле',
		 'Daewoo': 'Део',
		 'Hyundai': 'Хендай',
		 'Lexus': 'Лексус',
		 'Peugeot': 'Пежо',
		 'Renault': 'Рено',
		 'Skoda': 'Шкода',
		 'Toyota': 'Тойота',
		 'Volkswagen': 'Фольксваген',
		 'Volvo': 'Вольво',
		 'Opel': 'Опель'}